[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mammos-mmag"
version = "0.1.0"
description = "Finite element micromagnetic simulation tool."
readme = "README.md"
authors = [
  { name = "Thomas Schrefl" },
  { name = "Swapneel Amit Pathak" },
  { name = "Andrea Petrocchi" },
  { name = "Samuel Holt" },
  { name = "Martin Lang" },
  { name = "Hans Fangohr" },
]
license = { file = "LICENSE" }

classifiers = [
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Intended Audience :: Science/Research',
  'License :: OSI Approved :: BSD License',
  'Operating System :: POSIX',
  'Operating System :: Microsoft :: Windows',
  'Topic :: Scientific/Engineering :: Physics',
]

requires-python = ">=3.8"

# setuptools
[tool.setuptools.packages.find]
where = ["src"]

# pixi
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
cuda = ">=12.8.0,<13"
esys-escript = ">=5.10,<6"
meshio = "*"
jinja2 = ">=3.1.5,<4"
psutil = ">=7.0.0,<8"
pydantic = "*"
pyyaml = ">=6.0.2,<7"

[tool.pixi.pypi-dependencies]
mammos_mmag = { path = ".", editable = true }
jax = "*"

[tool.pixi.environments]
ruff = {features = ["ruff"]}
sphinx = {features = ["sphinx"]}
test = {features = ["test"]}
example = {features = ["example"]}

[tool.pixi.feature.ruff.dependencies]
ruff = "==0.8"
[tool.pixi.feature.ruff.tasks]
lint = "ruff check"
format = "ruff format"
clean = "ruff clean && py3clean ."

[tool.pixi.feature.sphinx.dependencies]
sphinx = "==8.1.3"
sphinx-rtd-theme = "==3.0.1"
numpy = "*"
[tool.pixi.feature.sphinx.tasks]
docs = "cd docs && make html"
docs-clean = "cd docs && make clean"

[tool.pixi.feature.test.dependencies]
polars = "*"
pytest = "*"
[tool.pixi.feature.test.tasks]
test = "pytest -v"

[tool.pixi.feature.example.dependencies]
jupyter = "*"
polars = "*"
[tool.pixi.feature.example.tasks]
example-materials = "jupyter-lab examples/materials_io.ipynb"
example-parameters = "jupyter-lab examples/parameters_io.ipynb"
# example-python-files = "jupyter-lab examples/run_python_files.ipynb"
example-unvtofly = "jupyter-lab examples/unvtofly.ipynb"
example-scripts = "jupyter-lab examples/scripts.ipynb"

[tool.ruff]
target-version = "py39"
line-length = 88
indent-width = 4
respect-gitignore = true
exclude = [
  "src/mammos_mmag/scripts/*.py", # scripts
  "examples", # to be checked
]

[tool.ruff.lint.per-file-ignores]
"src/mammos_mmag/tofly.py" = [
  "D101", # undocumented-public-class
  "D103", # undocumented-public-function
]

[tool.ruff.lint]
# Ruff default rules, pydocstyle, and pycodestyle warnings
select = ["D", "E4", "E7", "E9", "F", "W"]
ignore = []

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.format]
quote-style = "double"
