[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mammosmag"
version = "0.1.0"
description = "Finite element micromagnetic simulation tool."
readme = "README.md"
authors = [
  { name = "Thomas Schrefl" },
  { name = "Swapneel Amit Pathak" },
  { name = "Andrea Petrocchi" },
  { name = "Samuel Holt" },
  { name = "Martin Lang" },
  { name = "Hans Fangohr" },
]
license = { file = "LICENSE" }

classifiers = [
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Intended Audience :: Science/Research',
  'License :: OSI Approved :: BSD License',
  'Operating System :: POSIX',
  'Operating System :: Microsoft :: Windows',
  'Topic :: Scientific/Engineering :: Physics',
]

requires-python = ">=3.6"

[project.scripts]
mammosmag = "mammosmag.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
