[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mmag"
version = "0.1.0"
description = "Finite element micromagnetic simulation tool."
readme = "README.md"
authors = [
  { name = "Thomas Schrefl" },
  { name = "Swapneel Amit Pathak" },
  { name = "Andrea Petrocchi" },
  { name = "Samuel Holt" },
  { name = "Martin Lang" },
  { name = "Hans Fangohr" },
]
license = { file = "LICENSE" }

classifiers = [
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Intended Audience :: Science/Research',
  'License :: OSI Approved :: BSD License',
  'Operating System :: POSIX',
  'Operating System :: Microsoft :: Windows',
  'Topic :: Scientific/Engineering :: Physics',
]

requires-python = ">=3.8"

dependencies = [
  "jinja2",
]

[tool.setuptools.packages.find]
where = ["src"]

# pixi
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
mmag = { path = ".", editable = true }
PyYAML = "*"

[tool.pixi.tasks]
build = { cmd = [
  "python",
  "build.py",
  "$CONTAINER",
  "$THREADS",
  "$LOCATION"
], cwd = "tools", env = { CONTAINER = "apptainer", THREADS = "16", LOCATION = "" }}

[tool.pixi.feature.format.dependencies]
ruff = "==0.8"
[tool.pixi.feature.docs.dependencies]
sphinx = "==8.1.3"
sphinx-rtd-theme = "==3.0.1"
numpy = ">=2"
[tool.pixi.feature.test.dependencies]
pytest = "*"
[tool.pixi.feature.example.dependencies]
jupyter = "*"

[tool.pixi.environments]
format = {features = ["format"]}
docs = {features = ["docs"]}
test = {features = ["test"]}
example = {features = ["example"]}

[tool.pixi.feature.test.tasks]
test = "pytest -v"

[tool.pixi.feature.docs.tasks]
docs = "cd docs && make html"
docs-clean = "cd docs && make clean"

[tool.pixi.feature.format.tasks]
lint = "ruff check"
format = "ruff format"
clean = "ruff clean && py3clean ."

[tool.pixi.feature.example.tasks]
example-materials = "jupyter-lab examples/materials_io.ipynb"
example-parameters = "jupyter-lab examples/parameters_io.ipynb"
example-loop = "jupyter-lab examples/hysteresis_loop.ipynb"
example-python-files = "jupyter-lab examples/run_python_files.ipynb"
example-unvtofly = "jupyter-lab examples/unvtofly.ipynb"

[tool.ruff]
target-version = "py39"
line-length = 88
indent-width = 4
respect-gitignore = true
exclude = [
  "tools/scripts", # scripts not written by me (subject to changes)
  "tools/patches/", # patches
  "src/mmag/tofly.py", # to be checked
  "examples", # to be checked
]

[tool.ruff.lint]
# Ruff default rules, pydocstyle, and pycodestyle warnings
select = ["D", "E4", "E7", "E9", "F", "W"]
ignore = []

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.format]
quote-style = "double"
