name: Test Python distribution

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.44.0
    - name: Run tests
      run: pixi run test
    - name: Run lint and format
      run: pixi run pre-commit-all-files
