name: Build Hystmag docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          build-arg: BUILD_THREADS=4,RUN_THREADS=4
          tags: hystmag:latest
      -
        name: Test
        run: |
          docker run --volume mumag/pymag/examples/demagnetization:/io hystmag cube
